# 1. Frame the Problem
Create an ai that can be used in order to play a game of tetris by dropping and rotating pieces in order to last for as long as possible.

# 2. Get the Data
I have been provided a repository containing the already coded game of tetris along with genetic and greedy classes that can be used in order to help create my own ai to play the game for as long as possible. Additionally, there is a report from someone who already did the project which likely contains important insight into how to approach the problem.

# 3. Explore the Data
I have went through the paper and provided code and have gained an understanding of how to use functions from the various python files for training my ai and now have an idea of what the functions of my ai should look like.

# 4. Prepare the Data
I have cloned the repository into jupyter notebook and installed the required modules for the code of this project to run.

# 5. Model the Data
I have created my ai in the python file myalgo.py. In creating this ai I took inspiration from both the greedy and genetic ais provided and created an ai that uses functions such as valuate, get_best_move, and cost based upon those functions from those ais. The ai uses an init function that initializes attributes such as the genotype(the weights used for evalutaion), fit_score, fit_rel, and aggregate and allows for mutation based on certain conditions. The valuate function evaluates the state of a given board and gives it a rating based upon the height, number of holes, and lines cleared at the time it is called. The cost function evaluates the cost of a certain move based upon height, holes, bumpiness, and lines cleared, and returns a cost value based on these. The get_best_move function returns the best move chosen as a result of it having either a high valuation or low cost.

# 6. Fine Tune the Model
The model was trained using functions similar to those from the genetic_helpers python file and the training process can be seen below in the jupyter notebook. The stats of training can also be seen below and a genetic training process was used with a population of 50, 4 gens, and 5 trials. This process involved iteratively evolving and selecting agents beginning from random genotypes based on their fitness to ultimately find the agent with the best genotype for the ai to play tetris.

# 7. Present
After creating the functions of this ai and then training it with the genetic process, I have ultimately created an ai that is capable of clearing anywhere from 30-1000+ lines. This ai was created using inspirations from the genetic and greedy ais provided and makes use of modified versions of the cost, valuate, and get_best_move functions in order to create an ai that makes the best decisions to last as long as possible while playing tetris. This ai was then trained using the processes of a standard genetic algorithm, ultimately yielding one of the best agent genotypes for playing tetris.

# 8. Launch the Model System
In order to play tetris with the ai I created a python file in pycharms that reads the csv file created from the training and takes the top genotype from training and sets the agent equal to the ai with that genotype then runs the game with my ai.
Code from python file:
trained = pd.read_csv('training6.csv')
genotypes = trained[' top_gene'].tolist()
finalgenotyp= genotypes[0]6]
finalgenotype = np.array(finalgenotype)
agent = myai(genotype=finalgenotype, aggregate='lin', mutate=False)
g = Game(mode='myai')
g.run()

In [1]:
import numpy as np
import pandas as pd
import operator
from copy import copy, deepcopy
import random
from piece import BODIES, Piece
from board import Board
from myalgo import myai
from game import Game
from genetic_controller import compute_fitness

pygame 2.5.2 (SDL 2.28.2, Python 3.10.10)
Hello from the pygame community. https://www.pygame.org/contribute.html


In [2]:
population = 50
gens = 4
trials = 5
num_elite = 5
survival_rate=.2
logging_file='training6.csv'
headers = ['avg_fit','avg_gene', 'top_fit', 'top_gene', 'elite_fit', 'elite_gene']
pop = [myai(num_features = 3) for x in range(population)]

In [3]:
def cross(a1, a2):
    new_genotype = []
    a1_prop = a1.fit_rel / a2.fit_rel
    for i in range(len(a1.genotype)):
        rand = random.uniform(0, 1)
        if rand > a1_prop:
            new_genotype.append(a1.genotype[i])
        else:
            new_genotype.append(a2.genotype[i])

    return myai(genotype=np.array(new_genotype), aggregate='lin', mutate=True)

In [4]:
for gen in range(gens):

        total_fitness = 0
        top_agent = 0
        gene = np.zeros(3)

        for n in range(population):
            print(f"Agent: {n}/{population}")
            agent = pop[n]
            agent.fit_score = compute_fitness(agent, num_trials=trials)
            total_fitness += agent.fit_score 
            #try:
            print(agent.genotype)
            print(gene)
            gene+=agent.genotype


        for agent in pop:
            agent.fit_rel = agent.fit_score / total_fitness

        next_gen = []

        sorted_pop = sorted(pop, reverse=True)

        elite_fit_score = 0
        elite_genes = np.zeros(3)
        top_agent=sorted_pop[0]

        for i in range(num_elite):
            elite_fit_score +=sorted_pop[i].fit_score
            elite_genes += sorted_pop[i].genotype
            next_gen.append(myai(genotype=sorted_pop[i].genotype, mutate=False))

       
        num_parents = round(population * survival_rate)
        parents = sorted_pop[:num_parents]

        
        for _ in range(population-(num_elite)):
            
            parents = random.sample(parents, 2)
            next_gen.append(cross(parents[0], parents[1]))


        avg_fit = (total_fitness/population)
        avg_gene = (gene/population)
        top_fit = (top_agent.fit_score)
        top_gene = (top_agent.genotype)
        elite_fit = (elite_fit_score/num_elite)
        elite_gene = (elite_genes/num_elite)

        data = [[avg_fit, avg_gene, top_fit, top_gene, elite_fit, elite_gene]]
        df = pd.DataFrame(data, columns=headers)
        df.to_csv(f'data/{logging_file}.csv', mode='a', index=False, header=False)


        print(f'\nEpoch {gens}: \n    total fitness: {total_fitness/population}\n    best agent: {top_agent.fit_score}\n')

        pop = next_gen

Agent: 0/50
240 82
    Trial: 0/5
572 219
    Trial: 1/5
260 89
    Trial: 2/5
446 171
    Trial: 3/5
567 223
    Trial: 4/5
[ 0.69376355  0.45163306 -0.89019759]
[0. 0. 0.]
Agent: 1/50
26 2
    Trial: 0/5
23 3
    Trial: 1/5
25 3
    Trial: 2/5
22 3
    Trial: 3/5
20 3
    Trial: 4/5
[0.15433051 0.93780905 0.08055198]
[ 0.69376355  0.45163306 -0.89019759]
Agent: 2/50
25 0
    Trial: 0/5
12 0
    Trial: 1/5
18 1
    Trial: 2/5
19 1
    Trial: 3/5
51 13
    Trial: 4/5
[-0.49535723  0.53798583  0.04847324]
[ 0.84809406  1.38944211 -0.80964561]
Agent: 3/50
1648 675
    Trial: 0/5
312 110
    Trial: 1/5
619 238
    Trial: 2/5
1642 666
    Trial: 3/5
2174 889
    Trial: 4/5
[ 0.11674104 -0.10184196 -0.04845867]
[ 0.35273683  1.92742794 -0.76117237]
Agent: 4/50
30 4
    Trial: 0/5
21 1
    Trial: 1/5
15 0
    Trial: 2/5
22 1
    Trial: 3/5
12 2
    Trial: 4/5
[ 0.33665518 -0.90131179  0.82474522]
[ 0.46947787  1.82558598 -0.80963104]
Agent: 5/50
1113 448
    Trial: 0/5
286 102
    Trial: 1/5

In [6]:
trained = pd.read_csv('data/training6.csv')
genotypes = trained[' top_gene'].tolist()
finalgenotype = genotypes[0]
finalgenotype = np.array(finalgenotype)
finalgenotype

array('[-0.36464097 -0.48704628 -0.87621156]', dtype='<U37')

In [7]:
agent = myai(genotype=finalgenotype, aggregate='lin', mutate=False)
agent

In [8]:
%run main.py myai agent

464 177
